attributes:
  BuildIndependentTargetsInParallel: '1'
  LastSwiftUpdateCheck: '1420'
  LastUpgradeCheck: '1420'
configs:
  Debug: debug
  Release: release
name: GodVoiceWatch
options:
  defaultConfig: Release
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
settings:
  configs:
    Debug:
      CLANG_CXX_LANGUAGE_STANDARD: gnu++20
      MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
      MTL_FAST_MATH: 'YES'
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      SWIFT_OPTIMIZATION_LEVEL: -Onone
    Release:
      CLANG_CXX_LANGUAGE_STANDARD: gnu++20
      MTL_FAST_MATH: 'YES'
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
targets:
  GodVoiceWatch:
    dependencies:
    - target: GodVoiceWatch Watch App
    platform: iOS
    settings:
      configs:
        Debug:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_ASSET_PATHS: '"GodVoiceWatch/Preview Content"'
          GENERATE_INFOPLIST_FILE: 'YES'
          INFOPLIST_KEY_CFBundleDisplayName: GodVoiceWatch
          INFOPLIST_KEY_UIApplicationSceneManifest_Generation: 'YES'
          INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: 'YES'
          INFOPLIST_KEY_UILaunchScreen_Generation: 'YES'
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationPortrait
            UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft
            UIInterfaceOrientationLandscapeRight
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
            UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
          IPHONEOS_DEPLOYMENT_TARGET: '16.2'
          LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - '@executable_path/Frameworks'
          MARKETING_VERSION: '1.0'
          PRODUCT_BUNDLE_IDENTIFIER: com.subta.GodVoiceWatch
          SDKROOT: iphoneos
          SWIFT_EMIT_LOC_STRINGS: 'YES'
          SWIFT_VERSION: '5.0'
          TARGETED_DEVICE_FAMILY: 1,2
        Release:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_ASSET_PATHS: '"GodVoiceWatch/Preview Content"'
          GENERATE_INFOPLIST_FILE: 'YES'
          INFOPLIST_KEY_CFBundleDisplayName: GodVoiceWatch
          INFOPLIST_KEY_UIApplicationSceneManifest_Generation: 'YES'
          INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: 'YES'
          INFOPLIST_KEY_UILaunchScreen_Generation: 'YES'
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationPortrait
            UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft
            UIInterfaceOrientationLandscapeRight
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
            UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
          IPHONEOS_DEPLOYMENT_TARGET: '16.2'
          LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - '@executable_path/Frameworks'
          MARKETING_VERSION: '1.0'
          PRODUCT_BUNDLE_IDENTIFIER: com.subta.GodVoiceWatch
          SDKROOT: iphoneos
          SWIFT_EMIT_LOC_STRINGS: 'YES'
          SWIFT_VERSION: '5.0'
          TARGETED_DEVICE_FAMILY: 1,2
          VALIDATE_PRODUCT: 'YES'
    sources:
    - name: GodVoiceWatch
      path: GodVoiceWatch
    type: application
  GodVoiceWatch Watch App:
    platform: iOS
    settings:
      configs:
        Debug:
          ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_ASSET_PATHS: '"GodVoiceWatch Watch App/Preview Content"'
          GENERATE_INFOPLIST_FILE: 'YES'
          INFOPLIST_KEY_CFBundleDisplayName: GodVoiceWatch
          INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
            UIInterfaceOrientationPortraitUpsideDown
          INFOPLIST_KEY_WKCompanionAppBundleIdentifier: com.subta.GodVoiceWatch
          LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - '@executable_path/Frameworks'
          MARKETING_VERSION: '1.0'
          PRODUCT_BUNDLE_IDENTIFIER: com.subta.GodVoiceWatch.watchkitapp
          SDKROOT: watchos
          SKIP_INSTALL: 'YES'
          SWIFT_EMIT_LOC_STRINGS: 'YES'
          SWIFT_VERSION: '5.0'
          TARGETED_DEVICE_FAMILY: '4'
          WATCHOS_DEPLOYMENT_TARGET: '9.1'
        Release:
          ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_ASSET_PATHS: '"GodVoiceWatch Watch App/Preview Content"'
          GENERATE_INFOPLIST_FILE: 'YES'
          INFOPLIST_KEY_CFBundleDisplayName: GodVoiceWatch
          INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
            UIInterfaceOrientationPortraitUpsideDown
          INFOPLIST_KEY_WKCompanionAppBundleIdentifier: com.subta.GodVoiceWatch
          LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - '@executable_path/Frameworks'
          MARKETING_VERSION: '1.0'
          PRODUCT_BUNDLE_IDENTIFIER: com.subta.GodVoiceWatch.watchkitapp
          SDKROOT: watchos
          SKIP_INSTALL: 'YES'
          SWIFT_EMIT_LOC_STRINGS: 'YES'
          SWIFT_VERSION: '5.0'
          TARGETED_DEVICE_FAMILY: '4'
          VALIDATE_PRODUCT: 'YES'
          WATCHOS_DEPLOYMENT_TARGET: '9.1'
    sources:
    - name: GodVoiceWatch Watch App
      path: GodVoiceWatch Watch App
    type: application
